import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {normalizeAnnualVisitors} from '../annual-visitors.mjs';
import {groupCounts} from '../lib.mjs';
const source=JSON.parse(await readFile(new URL('../work/raw/kosis-annual-visitors.json',import.meta.url),'utf8'));
const result=normalizeAnnualVisitors(source);
test('KOSIS 실제 응답의 A 주기를 연간으로 처리하고 전체 원본셀을 보존한다',()=>{assert.equal(result.rows.length,source.data.length);assert.deepEqual(result.meta.years,[...new Set(source.data.map(r=>Number(r.PRD_DE)))].sort((a,b)=>a-b));for(const r of result.rows)assert.deepEqual(r.raw,result.meta.fields.map(f=>source.data[r.i-1][f]??null));});
test('전국 추이는 공식 총계만 사용하고 오동도는 별도 공원으로 연결하지 않는다',()=>{const national=result.rows.filter(r=>r.kind==='total');assert.equal(national.length,result.meta.years.length);assert.ok(result.rows.filter(r=>r.kind==='subset').every(r=>r.p===null));for(const total of national){const records=result.rows.filter(r=>r.y===total.y&&r.kind==='park');assert.ok(records.every(r=>r.p));if(records.every(r=>r.v!==null)){const comparison=groupCounts(records,r=>r.p,r=>r.v);assert.equal(comparison.reduce((s,r)=>s+r.value,0),total.v);}}});
test('결측·0·통계부호를 구분하고 잘못된 단위를 거부한다',()=>{const input=structuredClone(source),i=input.data.findIndex(r=>r.C1_NM==='지리산');input.data[i].DT='-';assert.equal(normalizeAnnualVisitors(input).rows[i].v,null);input.data[i].DT='0';assert.equal(normalizeAnnualVisitors(input).rows[i].v,0);input.data[i].DT='123p';assert.equal(normalizeAnnualVisitors(input).rows[i].v,null);input.data[i].UNIT_NM='천 명';assert.throws(()=>normalizeAnnualVisitors(input),/unit/);});
test('공원 자료를 생성하지 않고 중복 통계셀은 거부한다',()=>{assert.equal(result.rows.length,source.data.length);const input=structuredClone(source);input.data.push({...input.data[0]});input.totalCount++;assert.throws(()=>normalizeAnnualVisitors(input),/Duplicate/);});
