import test from 'node:test';import assert from 'node:assert/strict';import{readFile}from'node:fs/promises';import{parks,parkId,validDate,validYear,coordinatePair,groupCounts,csvCell}from'../lib.mjs';
const read=key=>readFile(new URL(`../site/data/${key}.json`,import.meta.url),'utf8').then(JSON.parse);
test('공원 ID는 확인된 이름만 연결하며 미등록·사무소·지질공원을 추정하지 않는다',()=>{assert.equal(parks.length,24);assert.equal(parkId(' 지리산 국립공원 '),'knps-jirisan');assert.equal(parkId('지리산경남사무소'),null);assert.equal(parkId('부산국가지질공원'),null);assert.equal(parkId('지리샨'),null);});
test('결측과 비정상 날짜·시공연도·좌표를 생성하거나 보정하지 않는다',()=>{assert.equal(validDate('2023-02-29'),null);assert.equal(validDate('2024-02-29'),'2024-02-29');assert.equal(validYear(88),null);assert.deepEqual(coordinatePair('35°48\'45.21"','129°22\'11.02"'),[35+48/60+45.21/3600,129+22/60+11.02/3600]);assert.deepEqual(coordinatePair('35°60\'0"','129'),[null,null]);assert.deepEqual(coordinatePair('',127),[null,null]);assert.deepEqual(coordinatePair(0,0),[null,null]);assert.deepEqual(coordinatePair(127,35),[null,null]);});
test('수집된 전체 행을 보존하고 공원별 집계 합계가 원본과 일치한다',async()=>{for(const key of ['roadkill','landslide','buildings','visitors','landscape']){const{meta,rows}=await read(key);const source=JSON.parse(await readFile(new URL(`../work/raw/source-${meta.id}.json`,import.meta.url),'utf8'));const count=source.totalCount;assert.ok(count>0);assert.equal(rows.length,count);assert.equal(rows.length,source.data.length);for(const r of rows)assert.deepEqual(r.raw,meta.fields.map(f=>source.data[r.i-1][f]??null));assert.equal(new Set(rows.map(r=>r.i)).size,count);if(meta.parkable)assert.equal(groupCounts(rows,r=>r.p).reduce((s,g)=>s+g.value,0),count);if(!meta.parkable)assert.ok(rows.every(r=>r.p===null));}});
test('같은 내용의 원본행은 별개 기록으로 보존하고 발생 총수로 변환하지 않는다',async()=>{const{meta,rows}=await read('roadkill');const source=JSON.parse(await readFile(new URL('../work/raw/source-3068387.json',import.meta.url),'utf8'));assert.equal(meta.duplicateRows,source.data.length-new Set(source.data.map(r=>JSON.stringify(r))).size);for(const g of groupCounts(rows,r=>r.p))assert.equal(g.value,source.data.filter(r=>parkId(r['국립공원명'])===g.label).length);});
test('산사태 좌표의 도분초 변환이 첫 원본과 일치한다',async()=>{const{rows}=await read('landslide');const {meta}=await read('landslide');for(const r of rows)assert.deepEqual([r.lat,r.lon],coordinatePair(r.raw[meta.fields.indexOf('위도')],r.raw[meta.fields.indexOf('경도')]));});
test('설악산 탐방객은 지점별 값과 일자만 합산하며 날짜·지점 중복이 없다',async()=>{const{meta,rows}=await read('visitors');const dates=rows.map(r=>r.d).filter(Boolean).sort();assert.deepEqual(meta.dates,[dates[0],dates.at(-1)]);const keys=new Set(rows.map(r=>JSON.stringify([r.d,r.raw[meta.fields.indexOf('관리지구')],r.l])));assert.equal(keys.size,rows.length);const point=rows.filter(r=>r.l===rows[0].l&&r.v!==null);const monthly=groupCounts(point,r=>r.d.slice(0,7),r=>r.v);assert.equal(monthly.reduce((s,g)=>s+g.value,0),point.reduce((s,r)=>s+r.v,0));});
test('CSV는 결측과 0을 구분하고 따옴표·줄바꿈·수식 문자열을 처리한다',()=>{assert.equal(csvCell(null),'""');assert.equal(csvCell(0),'"0"');assert.equal(csvCell('가,"나"\n다'),'"가,""나""\n다"');assert.equal(csvCell('=SUM(A1)'),"\"'=SUM(A1)\"");assert.equal(csvCell(' @formula'),"\"' @formula\"");assert.equal(csvCell(-1),'"-1"');});
